// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_aQNBlQkWJxyDKF8twQvuA0_EMC7pKc',
    appId: '1:622385369886:web:68e94c683521d9477aef0f',
    messagingSenderId: '622385369886',
    projectId: 'sms-spam-detector-b6ec1',
    authDomain: 'sms-spam-detector-b6ec1.firebaseapp.com',
    storageBucket: 'sms-spam-detector-b6ec1.appspot.com',
    measurementId: 'G-MHKMTR3C5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhrUsxDrpjGvtv5Lv8NHLSAjdUKbOcrY',
    appId: '1:622385369886:android:606bc300a6d622d17aef0f',
    messagingSenderId: '622385369886',
    projectId: 'sms-spam-detector-b6ec1',
    storageBucket: 'sms-spam-detector-b6ec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOlXyxPK2t6rb5B6sydsKlDKzOhtg_hxE',
    appId: '1:622385369886:ios:529ff2998080668b7aef0f',
    messagingSenderId: '622385369886',
    projectId: 'sms-spam-detector-b6ec1',
    storageBucket: 'sms-spam-detector-b6ec1.appspot.com',
    iosClientId: '622385369886-s1pbrrrup9glnr3nuddqd7862ne02n8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.smsSpamDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOlXyxPK2t6rb5B6sydsKlDKzOhtg_hxE',
    appId: '1:622385369886:ios:529ff2998080668b7aef0f',
    messagingSenderId: '622385369886',
    projectId: 'sms-spam-detector-b6ec1',
    storageBucket: 'sms-spam-detector-b6ec1.appspot.com',
    iosClientId: '622385369886-s1pbrrrup9glnr3nuddqd7862ne02n8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.smsSpamDetector',
  );
}
